Repository prgrms-web-devcourse-final-project/WEB3_4_Fr-End_BE, pull requests merged in 2025-04, with the labels that each got.

#41 Refactor/I-01 #39 : Gemini diff 관련 오류로 인해 프롬프트 수정
  .github/workflows/gemini-ai-code-review.yml
Labels: bug

#49 Feature/MB-01 #45 : Mateboard 멘토링 리뷰 반영 리팩토링
  backend/src/main/java/com/frend/planit/domain/mateboard/post/controller/.gitkeep
  backend/src/main/java/com/frend/planit/domain/mateboard/post/controller/MateController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/request/.gitkeep
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/request/MateRequestDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/.gitkeep
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/.gitkeep
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/AuthorGender.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/Mate.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/MateGender.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/RecruitmentStatus.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/TravelRegion.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/.gitkeep
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/.gitkeep
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
  backend/src/main/java/com/frend/planit/global/response/ApiResponse.java
  backend/src/main/java/com/frend/planit/global/validation/CodeValidation.java
Labels: refactor

#50 Feature/C-01 #25 : CalendarCd 리뷰 후 Refector
  backend/src/main/java/com/frend/planit/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/frend/planit/domain/calendar/dto/request/CalendarRequestDto.java
  backend/src/main/java/com/frend/planit/domain/calendar/entity/CalendarEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/exception/CalendarNotFoundException.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarService.java
  backend/src/test/java/com/frend/planit/domain/calendar/CalendarTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/calendar/controller/CalendarControllerTest.java
Labels: refactor, fix

#54 Refactor/G-03 : 불필요한 ApiResponseHelper 삭제
  backend/src/main/java/com/frend/planit/domain/mateboard/post/controller/MateController.java
  backend/src/main/java/com/frend/planit/global/exception/handler/CommonExceptionHandler.java
  backend/src/main/java/com/frend/planit/global/exception/handler/ServiceExceptionHandler.java
  backend/src/main/java/com/frend/planit/global/exception/handler/ValidationExceptionHandler.java
  backend/src/main/java/com/frend/planit/global/response/ApiResponse.java
  backend/src/main/java/com/frend/planit/global/response/ApiResponseHelper.java
  backend/src/main/java/com/frend/planit/global/validation/CodeValidation.java
  backend/src/test/java/com/frend/planit/global/GlobalTestController.java
  backend/src/test/java/com/frend/planit/global/exception/ExceptionHandlerTest.java
Labels: refactor

#67 Feature/U-02 #62 : logout, jwt token refresh, @AuthenticationPrincipal 이용
  backend/src/main/java/com/frend/planit/domain/auth/client/GoogleOauthClient.java
  backend/src/main/java/com/frend/planit/domain/auth/client/OAuthClient.java
  backend/src/main/java/com/frend/planit/domain/auth/client/OAuthClientFactory.java
  backend/src/main/java/com/frend/planit/domain/auth/controller/AuthController.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/request/SocialLoginRequest.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/request/TokenRefreshRequest.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/response/GoogleTokenResponse.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/response/GoogleUserInfoResponse.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/response/SocialLoginResponse.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/response/TokenRefreshResponse.java
  backend/src/main/java/com/frend/planit/domain/auth/service/AuthService.java
  backend/src/main/java/com/frend/planit/domain/auth/service/RefreshTokenRedisService.java
  backend/src/main/java/com/frend/planit/domain/user/controller/UserController.java
  backend/src/main/java/com/frend/planit/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/frend/planit/domain/user/service/UserService.java
  backend/src/main/java/com/frend/planit/global/security/.gitkeep
  backend/src/main/java/com/frend/planit/global/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/frend/planit/global/security/JwtTokenProvider.java
  backend/src/main/java/com/frend/planit/global/security/SecurityConfig.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/frend/planit/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/frend/planit/domain/user/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/user/controller/UserControllerTest.java
Labels: enhancement

#74 Feature/A-01 #55 : TourAPI 동기화 및 CRUD
  backend/build.gradle
  backend/src/main/java/com/frend/planit/PlanitApplication.java
  backend/src/main/java/com/frend/planit/domain/accommodation/client/TourApiClient.java
  backend/src/main/java/com/frend/planit/domain/accommodation/controller/AccommodationController.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/request/AccommodationRequestDto.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/response/AccommodationResponseDto.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/tourapi/TourApiBody.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/tourapi/TourApiItem.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/tourapi/TourApiResponse.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/tourapi/TourApiXmlWrapper.java
  backend/src/main/java/com/frend/planit/domain/accommodation/entity/AccommodationEntity.java
  backend/src/main/java/com/frend/planit/domain/accommodation/loader/AccommodationInitialDataLoader.java
  backend/src/main/java/com/frend/planit/domain/accommodation/repository/AccommodationRepository.java
  backend/src/main/java/com/frend/planit/domain/accommodation/scheduler/AccommodationSyncScheduler.java
  backend/src/main/java/com/frend/planit/domain/accommodation/service/AccommodationService.java
  backend/src/main/java/com/frend/planit/domain/accommodation/type/.gitkeep
  backend/src/main/java/com/frend/planit/domain/accomodation/dto/request/.gitkeep
  backend/src/main/java/com/frend/planit/domain/accomodation/dto/response/.gitkeep
  backend/src/main/java/com/frend/planit/domain/accomodation/entity/.gitkeep
  backend/src/main/java/com/frend/planit/domain/accomodation/repository/.gitkeep
  backend/src/main/java/com/frend/planit/domain/accomodation/service/.gitkeep
  backend/src/main/java/com/frend/planit/domain/accomodation/type/.gitkeep
  backend/src/main/java/com/frend/planit/global/config/RestTemplateConfig.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
  backend/src/main/resources/application-test.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/frend/planit/domain/accommodation/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/accommodation/service/.gitkeep
Labels: enhancement, refactor

#70 Feature/Im-01 : 이미지 업로드 구현
  backend/build.gradle
  backend/src/main/java/com/frend/planit/domain/image/controller/ImageController.java
  backend/src/main/java/com/frend/planit/domain/image/dto/response/ImageResponse.java
  backend/src/main/java/com/frend/planit/domain/image/dto/response/UploadResponse.java
  backend/src/main/java/com/frend/planit/domain/image/entity/Image.java
  backend/src/main/java/com/frend/planit/domain/image/repository/ImageRepository.java
  backend/src/main/java/com/frend/planit/domain/image/service/ImageService.java
  backend/src/main/java/com/frend/planit/domain/image/type/HolderType.java
  backend/src/main/java/com/frend/planit/domain/image/type/ImageMimeType.java
  backend/src/main/java/com/frend/planit/domain/picture/controller/.gitkeep
  backend/src/main/java/com/frend/planit/domain/picture/dto/request/.gitkeep
  backend/src/main/java/com/frend/planit/domain/picture/dto/response/.gitkeep
  backend/src/main/java/com/frend/planit/domain/picture/entity/.gitkeep
  backend/src/main/java/com/frend/planit/domain/picture/repository/.gitkeep
  backend/src/main/java/com/frend/planit/domain/picture/service/.gitkeep
  backend/src/main/java/com/frend/planit/domain/picture/type/.gitkeep
  backend/src/main/java/com/frend/planit/global/aws/.gitkeep
  backend/src/main/java/com/frend/planit/global/aws/s3/S3PresignedPostResponse.java
  backend/src/main/java/com/frend/planit/global/aws/s3/S3Service.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
  backend/src/main/java/com/frend/planit/standard/util/.gitkeep
  backend/src/main/java/com/frend/planit/standard/util/RandomUtil.java
  backend/src/test/java/com/frend/planit/domain/image/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/image/service/.gitkeep
Labels: enhancement

#77 Feature/S-02 #46 : 여행 일정 (Travel) CRUD 구현
  backend/src/main/java/com/frend/planit/domain/accommodation/loader/AccommodationInitialDataLoader.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/day/entity/ScheduleDayEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/day/repository/ScheduleDayRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/entity/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/entity/ScheduleEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/repository/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/repository/ScheduleRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/controller/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelController.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/request/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/request/TravelRequest.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/response/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/response/DailyTravelResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/response/TravelResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/entity/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/entity/TravelEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/repository/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/repository/TravelRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/service/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelService.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/travelUtils/TravelGroupingUtils.java
  backend/src/main/java/com/frend/planit/global/initdata/.gitkeep
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
  backend/src/test/resources/application.yml
  db_local.mv.db
Labels: enhancement

#82 Feature/S-01 #24 : 여행 일정 (Schedule) CRUD 구현
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/controller/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleController.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/request/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/request/ScheduleRequest.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/response/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/response/ScheduleResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/entity/ScheduleEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/service/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/service/ScheduleService.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/request/TravelRequest.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/entity/TravelEntity.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: enhancement

#83 Feature/MB-02 #65 : 게시글 전체 조회 필터링 기능 적용 및 User 연동
  backend/build.gradle
  backend/src/main/java/com/frend/planit/domain/mateboard/post/controller/MateController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/request/MateRequestDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/AuthorGender.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/Mate.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/mapper/MateMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
  backend/src/main/java/com/frend/planit/global/config/QuerydslConfig.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
Labels: enhancement

#80 Feature/Im-02 : 이미지 조회 기능 추가
  backend/src/main/java/com/frend/planit/domain/image/controller/ImageController.java
  backend/src/main/java/com/frend/planit/domain/image/dto/response/ImageResponse.java
  backend/src/main/java/com/frend/planit/domain/image/dto/response/UploadResponse.java
  backend/src/main/java/com/frend/planit/domain/image/repository/ImageRepository.java
  backend/src/main/java/com/frend/planit/domain/image/service/ImageService.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
Labels: enhancement

#81 Feature/Im-03 : 이미지 교체 기능 추가
  backend/src/main/java/com/frend/planit/domain/image/controller/ImageController.java
  backend/src/main/java/com/frend/planit/domain/image/entity/Image.java
  backend/src/main/java/com/frend/planit/domain/image/service/ImageService.java
Labels: enhancement

#88 Feature/A-02 #57 : DB저장 시, Null 이슈 해결
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/tourapi/TourApiBody.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/tourapi/TourApiItems.java
Labels: bug, fix

#89 Feature/MB-03 #64: 메이트 모집 기능 구현
  backend/src/main/java/com/frend/planit/domain/mateboard/application/controller/MateApplicationController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/entity/MateApplication.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/entity/MateApplicationStatus.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/repository/MateApplicationRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/service/MateApplicationService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/request/MateRequestDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/Mate.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/mapper/MateMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
Labels: enhancement

#92 Feature/Im-04 #79: 이미지 삭제 기능 구현
  .gitignore
  backend/src/main/generated/com/frend/planit/domain/accommodation/entity/QAccommodationEntity.java
  backend/src/main/generated/com/frend/planit/domain/calendar/entity/QCalendarEntity.java
  backend/src/main/generated/com/frend/planit/domain/calendar/schedule/day/entity/QScheduleDayEntity.java
  backend/src/main/generated/com/frend/planit/domain/calendar/schedule/entity/QScheduleEntity.java
  backend/src/main/generated/com/frend/planit/domain/calendar/schedule/travel/entity/QTravelEntity.java
  backend/src/main/generated/com/frend/planit/domain/image/entity/QImage.java
  backend/src/main/generated/com/frend/planit/domain/mateboard/comment/entity/QMateComment.java
  backend/src/main/generated/com/frend/planit/domain/mateboard/post/entity/QMate.java
  backend/src/main/generated/com/frend/planit/domain/user/entity/QUser.java
  backend/src/main/generated/com/frend/planit/global/base/QBaseEntity.java
  backend/src/main/generated/com/frend/planit/global/base/QBaseTime.java
  backend/src/main/java/com/frend/planit/domain/image/entity/Image.java
  backend/src/main/java/com/frend/planit/domain/image/repository/ImageRepository.java
  backend/src/main/java/com/frend/planit/domain/image/service/ImageService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
  backend/src/main/java/com/frend/planit/global/aws/s3/S3Service.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
Labels: enhancement

#94 Feature/G-09 #93: 기본 데이터 코드 골자 작성
  backend/build.gradle
  backend/src/main/java/com/frend/planit/global/config/DataInitializer.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/static/s3-upload-test.html
Labels: enhancement

#98 Feature/A-02 #57 : [Refactor] Paging, Response, TamporaryNull
  backend/src/main/java/com/frend/planit/domain/accommodation/controller/AccommodationController.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/response/AccommodationResponseDto.java
  backend/src/main/java/com/frend/planit/domain/accommodation/entity/AccommodationEntity.java
  backend/src/main/java/com/frend/planit/domain/accommodation/service/AccommodationService.java
Labels: bug, refactor

#99 Feature/C-01 #25 : CRUD 및 로직 개선
  backend/src/main/java/com/frend/planit/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/frend/planit/domain/calendar/dto/request/CalendarRequestDto.java
  backend/src/main/java/com/frend/planit/domain/calendar/dto/response/CalendarResponseDto.java
  backend/src/main/java/com/frend/planit/domain/calendar/entity/CalendarEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/exception/CalendarException.java
  backend/src/main/java/com/frend/planit/domain/calendar/exception/CalendarNotFoundException.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/frend/planit/global/config/DataInitializer.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
  backend/src/test/java/com/frend/planit/domain/calendar/controller/CalendarControllerTest.java
Labels: refactor

#100 Feature/C-01 #25 : paging 개선, getAll제거
  backend/src/main/java/com/frend/planit/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/frend/planit/global/response/PageResponse.java
Labels: refactor

#101 Feature/C-02 #26 : 캘린터 초대 및 공유 기능
  backend/src/main/java/com/frend/planit/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/frend/planit/domain/calendar/entity/CalendarEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/entity/SharedCalendarEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/invitation/dto/request/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/invitation/dto/response/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/invitation/service/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/invitation/type/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/invite/controller/InviteController.java
  backend/src/main/java/com/frend/planit/domain/calendar/invite/dto/request/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/invite/dto/response/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/invite/entity/InviteEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/invite/repository/InviteRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/invite/service/InviteService.java
  backend/src/main/java/com/frend/planit/domain/calendar/invite/type/.gitkeep
  backend/src/main/java/com/frend/planit/domain/calendar/repository/SharedCalendarRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarPermissionValidator.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/SharedCalendarService.java
  backend/src/main/java/com/frend/planit/global/config/DataInitializer.java
  backend/src/main/java/com/frend/planit/global/response/ErrorType.java
Labels: enhancement, refactor

#103 Feature/A-02 #57 : CrawlingAllArea, DeleteLog
  backend/src/main/java/com/frend/planit/domain/accommodation/client/TourApiClient.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/response/AccommodationResponseDto.java
  backend/src/main/java/com/frend/planit/domain/accommodation/entity/AccommodationEntity.java
  backend/src/main/java/com/frend/planit/domain/accommodation/loader/AccommodationInitialDataLoader.java
  backend/src/main/java/com/frend/planit/domain/accommodation/scheduler/AccommodationSyncScheduler.java
  backend/src/main/java/com/frend/planit/domain/accommodation/service/AccommodationService.java
Labels: refactor

#104 Refactor/MB-01 #91: 메이트 게시판 테스트 작성
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/controller/MateCommentController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/dto/request/MateCommentRequestDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/dto/response/MateCommentResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/entity/MateComment.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/mapper/MateCommentMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/service/MateCommentService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/request/MateRequestDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/Mate.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
  backend/src/main/java/com/frend/planit/global/base/BaseTime.java
  backend/src/test/java/com/frend/planit/domain/board/mate/post/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/mate/post/service/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/comment/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/comment/dto/request/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/comment/dto/response/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/comment/entity/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/comment/repository/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/comment/service/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/comment/type/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/post/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/post/dto/request/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/post/dto/response/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/post/entity/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/post/repository/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/post/service/.gitkeep
  backend/src/test/java/com/frend/planit/domain/board/travel/post/type/.gitkeep
  backend/src/test/java/com/frend/planit/domain/mateboard/application/controller/MateApplicationControllerTest.java
  backend/src/test/java/com/frend/planit/domain/mateboard/comment/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/mateboard/comment/controller/MateCommentControllerTest.java
  backend/src/test/java/com/frend/planit/domain/mateboard/comment/service/.gitkeep
  backend/src/test/java/com/frend/planit/domain/mateboard/post/controller/MateControllerTest.java
  backend/src/test/java/com/frend/planit/domain/mateboard/post/service/MateServiceTest.java
  backend/src/test/java/com/frend/planit/testsecurity/UserTestFactory.java
  backend/src/test/java/com/frend/planit/testsecurity/WithMockCustomUser.java
  backend/src/test/java/com/frend/planit/testsecurity/WithMockCustomUserSecurityContextFactory.java
  backend/src/test/resources/sql/delete.sql
  backend/src/test/resources/sql/init-expired-mate.sql
  backend/src/test/resources/sql/init-full-applications.sql
  backend/src/test/resources/sql/init.sql
Labels: refactor

#111 [Refactor] Calendar-중복성제거,간결성,가독성유지
  backend/src/main/java/com/frend/planit/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/frend/planit/domain/calendar/entity/CalendarEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/exception/CalendarException.java
  backend/src/main/java/com/frend/planit/domain/calendar/invite/controller/InviteController.java
  backend/src/main/java/com/frend/planit/domain/calendar/invite/service/InviteService.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarPermissionValidator.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/SharedCalendarService.java
Labels: refactor

#113 Refactor/S-01 #105 : ScheduleService 검증 로직 리팩토링 및 여행지 정렬 로직 추가
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleController.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/day/entity/ScheduleDayEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/entity/ScheduleEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/service/ScheduleService.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/response/DailyTravelResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/entity/TravelEntity.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: refactor

#116 Refactor/MB-02 : 유저 연동 이슈 수정
  backend/src/main/java/com/frend/planit/domain/mateboard/application/controller/MateApplicationController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/entity/MateApplication.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/controller/MateCommentController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/entity/MateComment.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/controller/MateController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/Mate.java
  backend/src/test/java/com/frend/planit/domain/mateboard/post/controller/MateControllerTest.java
  backend/src/test/java/com/frend/planit/testsecurity/WithMockCustomUserSecurityContextFactory.java
Labels: bug

#120 Refactor/RU-02 #118 : 회원가입 requestDto 수정
  backend/src/main/java/com/frend/planit/domain/auth/dto/request/LocalRegisterRequest.java
Labels: refactor

#117 Feature/Im-04 #79: 이미지 리팩토링 및 테스트 코드 작성
  .gitignore
  backend/src/main/java/com/frend/planit/domain/image/service/ImageService.java
  backend/src/main/java/com/frend/planit/domain/image/type/HolderType.java
  backend/src/test/java/com/frend/planit/domain/image/ImageIntegrationTest.java
  backend/src/test/java/com/frend/planit/domain/image/controller/.gitkeep
  backend/src/test/java/com/frend/planit/domain/image/controller/ImageTestController.java
  backend/src/test/java/com/frend/planit/domain/image/dto/request/ImageTestRequest.java
  backend/src/test/java/com/frend/planit/domain/image/dto/response/ImageTestResponse.java
  backend/src/test/java/com/frend/planit/domain/image/entity/ImageTestEntity.java
  backend/src/test/java/com/frend/planit/domain/image/repository/ImageTestRepository.java
  backend/src/test/java/com/frend/planit/domain/image/service/.gitkeep
  backend/src/test/java/com/frend/planit/domain/image/service/ImageTestService.java
  backend/src/test/java/com/frend/planit/global/exception/ExceptionHandlerTest.java
Labels: enhancement

#122 Feature/C-03 #27 : LabelColor 추가 / SchemaForFE
  backend/src/main/java/com/frend/planit/domain/calendar/dto/request/CalendarRequestDto.java
  backend/src/main/java/com/frend/planit/domain/calendar/dto/response/CalendarResponseDto.java
  backend/src/main/java/com/frend/planit/domain/calendar/entity/CalendarEntity.java
Labels: enhancement, fix

#123 Feature/U-05 #107 : 내부 회원가입 로직
  backend/src/main/java/com/frend/planit/domain/auth/controller/AuthController.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/request/LocalLoginRequest.java
  backend/src/main/java/com/frend/planit/domain/auth/dto/request/LocalRegisterRequest.java
  backend/src/main/java/com/frend/planit/domain/user/controller/UserProfileUpdateController.java
  backend/src/main/java/com/frend/planit/domain/user/dto/request/UserFirstInfoRequest.java
  backend/src/main/java/com/frend/planit/domain/user/dto/request/UserUpdatePasswordRequest.java
  backend/src/main/java/com/frend/planit/domain/user/entity/User.java
  backend/src/main/java/com/frend/planit/domain/user/service/UserProfileUpdateService.java
  backend/src/main/java/com/frend/planit/global/init/auth/LocalUserBaseInitData.java
  backend/src/test/java/com/frend/planit/TestConfig.java
  backend/src/test/java/com/frend/planit/domain/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/frend/planit/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/frend/planit/domain/user/controller/UserProfileUpdateControllerTest.java
Labels: enhancement

#128 Refactor/S-01 #127 : ScheduleDay 날짜 오름차순 정렬 및 travelCount 오류 수정
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/repository/ScheduleRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/service/ScheduleService.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/request/TravelRequest.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/entity/TravelEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelService.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/travelUtils/TravelGroupingUtils.java
Labels: refactor

#131 Feature/Im-05 #121: 이미지-유저 연동
  backend/src/main/java/com/frend/planit/domain/accommodation/loader/AccommodationInitialDataLoader.java
  backend/src/main/java/com/frend/planit/domain/image/dto/response/ImageResponse.java
  backend/src/main/java/com/frend/planit/domain/image/dto/response/ImagesResponse.java
  backend/src/main/java/com/frend/planit/domain/image/repository/ImageRepository.java
  backend/src/main/java/com/frend/planit/domain/image/service/ImageService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
  backend/src/main/java/com/frend/planit/domain/user/controller/UserProfileUpdateController.java
  backend/src/main/java/com/frend/planit/domain/user/dto/request/UserUpdateProfileImageRequest.java
  backend/src/main/java/com/frend/planit/domain/user/service/UserProfileUpdateService.java
  backend/src/main/java/com/frend/planit/global/config/DataInitializer.java
  backend/src/main/java/com/frend/planit/global/init/auth/LocalUserBaseInitData.java
  backend/src/test/java/com/frend/planit/domain/image/ImageIntegrationTest.java
  backend/src/test/java/com/frend/planit/domain/image/dto/response/ImageTestResponse.java
  backend/src/test/java/com/frend/planit/domain/image/service/ImageTestService.java
  backend/src/test/java/com/frend/planit/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/frend/planit/domain/user/controller/UserProfileUpdateControllerTest.java
Labels: enhancement

#135 Feat/U-06 # 133 : 로컬 로그인시 socialid = null 로 직접 주입
  backend/src/main/java/com/frend/planit/domain/auth/dto/request/LocalRegisterRequest.java
  backend/src/test/java/com/frend/planit/domain/auth/controller/AuthControllerTest.java
Labels: fix

#137 Refactor/S-02 #134 : Travel 테스트 코드 오류 수정
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: refactor

#136 [Refactor] MB-01 #130 : 게시글 id 값, 댓글 id 값 반환
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/dto/response/MateCommentResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/mapper/MateCommentMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/mapper/MateMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
Labels: refactor

#139 Feature/A-02 #57 : 한도증가, TourApi 응답 예외 방어 추가
  backend/src/main/java/com/frend/planit/domain/accommodation/client/TourApiClient.java
  backend/src/main/java/com/frend/planit/domain/accommodation/controller/AccommodationController.java
  backend/src/main/java/com/frend/planit/domain/accommodation/dto/tourapi/TourApiItem.java
  backend/src/main/java/com/frend/planit/domain/accommodation/loader/AccommodationInitialDataLoader.java
  backend/src/main/java/com/frend/planit/domain/accommodation/scheduler/AccommodationSyncScheduler.java
  backend/src/main/java/com/frend/planit/domain/accommodation/service/AccommodationService.java
  backend/src/main/java/com/frend/planit/global/config/DataInitializer.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: enhancement, refactor

#140 Feature/Im-06 #132: 이미지-메이트 연동
  backend/src/main/java/com/frend/planit/domain/image/service/ImageService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
Labels: enhancement

#143 Feature/C-03 #27 : [Refactor] @builder.Default/@AuthenticationPrincipal
  backend/src/main/java/com/frend/planit/domain/calendar/controller/CalendarController.java
  backend/src/main/java/com/frend/planit/domain/calendar/entity/CalendarEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/invite/controller/InviteController.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: refactor

#144 Refactor/S-01 #142 : Schedule, ScheduleDay, Travel Response 응답 id 추가
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/response/ScheduleResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/entity/ScheduleEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelController.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/response/TravelResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/entity/TravelEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelService.java
Labels: refactor

#146 Refactor/CB-01 #129 : 챗봇 로그인 사용자 일정 조회 기능 오류 수정
  backend/src/main/java/com/frend/planit/global/config/DataInitializer.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: refactor

#148 Feature/U-07 : 내 활동 내역 (메이트 게시판, 댓글)
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/dto/response/MateCommentResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/mapper/MateCommentMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/repository/MateCommentRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/service/MateCommentService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
  backend/src/main/java/com/frend/planit/domain/user/controller/UserController.java
  backend/src/main/java/com/frend/planit/domain/user/service/UserService.java
  backend/src/test/java/com/frend/planit/domain/user/controller/UserControllerTest.java
Labels: enhancement

#150 Feature/U-08 : 내 활동 내역 - 캘린더 조회
  backend/src/main/java/com/frend/planit/domain/calendar/dto/response/CalendarActivityResponseDto.java
  backend/src/main/java/com/frend/planit/domain/calendar/repository/CalendarRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/service/CalendarService.java
  backend/src/main/java/com/frend/planit/domain/user/controller/UserController.java
  backend/src/main/java/com/frend/planit/domain/user/service/UserService.java
  backend/src/test/java/com/frend/planit/domain/user/controller/UserControllerTest.java
Labels: enhancement

#152 [Bug/UB-02 #151] : 카카오 네이버 오류 해결
  backend/src/main/java/com/frend/planit/domain/auth/client/KakaoOAuthClient.java
  backend/src/main/java/com/frend/planit/global/config/WebClientConfig.java
Labels: bug

#155 Refactor/S-01 #154 : 스케줄 전체 조회 기능 추가
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleController.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/response/ScheduleResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/repository/ScheduleRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/service/ScheduleService.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleControllerTest.java
Labels: refactor

#164 Refactor/S-02 #157 : 여행 일정 API 로그인 사용자 인증 기반 접근 제어 적용
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/request/ScheduleRequest.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/dto/response/ScheduleResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/entity/ScheduleEntity.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/service/ScheduleService.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelController.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelService.java
  backend/src/main/java/com/frend/planit/domain/chatbot/chatMessage/service/AIChatMessageService.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: refactor

#166 Refactor/S-02 #165 : 스케줄 blockColor null 반환 버그 수정 및 리팩토링
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/entity/ScheduleEntity.java
  backend/src/main/java/com/frend/planit/global/config/DataInitializer.java
Labels: fix

#167 Feature/MB-05 #163 : 댓글 좋아요 구현
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/controller/MateCommentLikeController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/entity/MateCommentLike.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/repository/MateCommentLikeRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/service/MateCommentLikeService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MatePostLikeService.java
Labels: enhancement

#168 Refactor/P-01 #161 : 예약건, 메이트 모집 글 스케쥴링 기능 구현
  backend/src/main/java/com/frend/planit/domain/booking/dto/request/PaymentCompleteRequest.java
  backend/src/main/java/com/frend/planit/domain/booking/repository/BookingRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateRepository.java
  backend/src/main/java/com/frend/planit/scheduler/StatusUpdateScheduler.java
Labels: enhancement

#173 Refactor/S-01 #171 : TravelResponse 값에 scheduleDayId 누락으로 인한 CURD 오류 수정
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/response/TravelResponse.java
Labels: bug

#172 Hotfix/mateboard : fetch join 수정
  backend/src/main/java/com/frend/planit/domain/booking/dto/request/PaymentCompleteRequest.java
  backend/src/main/java/com/frend/planit/domain/booking/service/BookingQueryService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
Labels: bug

#175 [Hotfix] 메이트 게시글 group by 추가
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
Labels: bug

#176 mateboard 이미지 부분 수정
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
Labels: bug

#177 Hotfix/mateboard : bio null 값 수정, 동행 신청 여부 판단 필드 추가
  backend/src/main/java/com/frend/planit/domain/mateboard/application/repository/MateApplicationRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/controller/MateController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/mapper/MateMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
Labels: bug

#179 Hotfix/mateboard: 게시글 좋아요, 댓글 좋아요 배열 반영
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/controller/MateCommentLikeController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/dto/response/CommentLikeInfo.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/dto/response/MateCommentResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/entity/MateComment.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/mapper/MateCommentMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/comment/service/MateCommentService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/CommentLikeInfo.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateApplicationInfo.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/PostLikeInfo.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/entity/Mate.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/mapper/MateMapper.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/service/MateService.java
Labels: fix

#180 Refactor/S-01 #170: Dto 리팩토링
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/day/repository/ScheduleDayRepository.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelController.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/dto/response/AllTravelsResponse.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelService.java
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/travel/travelUtils/TravelGroupingUtils.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
Labels: enhancement

#184 hotfix/Payment : 예약 상태 null값 예약 완료로 수정
  backend/src/main/java/com/frend/planit/domain/booking/entity/Booking.java
  backend/src/main/java/com/frend/planit/domain/booking/service/BookingQueryService.java
Labels: bug, fix

#188 Feature/U-09 #185 : 메이트 신청 페이지 (내 활동 내역)
  backend/src/main/java/com/frend/planit/domain/mateboard/application/dto/response/MateApplicationReceivedResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/dto/response/MateApplicationSentResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/repository/MateApplicationRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/application/service/MateApplicationService.java
  backend/src/main/java/com/frend/planit/domain/user/controller/UserController.java
  backend/src/main/java/com/frend/planit/domain/user/service/UserService.java
  backend/src/test/java/com/frend/planit/domain/user/controller/UserControllerTest.java
Labels: enhancement

#187 Feature/I-03 #186: Prometheus 연동
  backend/src/main/java/com/frend/planit/global/security/SecurityConfig.java
  backend/src/main/resources/application.yml
Labels: enhancement

#190 Feature/S-01 #170 : Schedule, Travel 도메인 테스트 코드 작성
  backend/src/main/java/com/frend/planit/domain/calendar/schedule/service/ScheduleService.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/controller/ScheduleControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/controller/TravelControllerTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/schedule/travel/service/TravelServiceTest.java
  backend/src/test/java/com/frend/planit/domain/calendar/service/.gitkeep
  backend/src/test/java/com/frend/planit/domain/calendar/service/ScheduleServiceTest.java
Labels: refactor

#192 Feature/CB-01 : 프롬프트 수정, 모델 변경
  backend/src/main/java/com/frend/planit/domain/chatbot/chatMessage/service/AIChatMessageService.java
  backend/src/main/java/com/frend/planit/domain/chatbot/chatbotUtils/AIUserContextHelper.java
  backend/src/main/resources/application.yml
Labels: refactor

#194 Refactor/G-06 #44: 로그 기능 개선
  backend/src/main/java/com/frend/planit/global/logging/LogBuilder.java
  backend/src/main/java/com/frend/planit/global/logging/aspect/ExceptionLoggingAspect.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/logback-spring.xml
Labels: refactor

#196 Feature/M-01: 메일링 테스트 코드 삭제
  backend/src/main/java/com/frend/planit/domain/mail/service/MailService.java
Labels: bug

#197 feature/M-01 : 전체 게시글 좋아요 여부 기능 구현
  backend/src/main/java/com/frend/planit/domain/mail/service/MailService.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/controller/MateController.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/dto/response/MateResponseDto.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MatePostLikeRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepository.java
  backend/src/main/java/com/frend/planit/domain/mateboard/post/repository/MateQueryRepositoryImpl.java
Labels: bug
